name: Build

on:
  push:
  pull_request:
  workflow_call:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14] # TODO: how can we reasonably select arch, when that's meaningful?
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install meson==1.4.0 ninja
      - name: Configure Project
        run: meson setup build/ -Dbuildtype=release
        env:
          CC: clang
      - name: Build and create dist
        run: meson install -C build --destdir install
      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ runner.os }}-${{ runner.arch }}
          path: |
            build/install/**/*