name: Build

on:
  push:
  pull_request:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      
      - name: Download LIPO
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop";
          Invoke-WebRequest https://github.com/konoui/lipo/releases/latest/download/lipo_Linux_amd64 -OutPath /tmp/lipo
          chmod +x /tmp/lipo

      - name: Build
        shell: pwsh
        run: |
          ./build.ps1 -LipoCommand /tmp/lipo

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            build/*.zip