name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version
      description:
        type: string
        required: false
        description: Description
        
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  release:
    needs: build
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download release artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: release-*
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release-*"
        body: false
        generateReleaseNotes: true
        tag: v${{ inputs.version }}
        